# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'kiwiTraffic' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for kiwiTraffic

  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'

  pod 'react-native-netinfo', :path => '../node_modules/@react-native-community/netinfo'

  target 'kiwiTrafficTests' do
    inherit! :search_paths
    # Pods for testing
  end

end